DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'petwork') THEN
        CREATE SCHEMA petwork;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS petwork."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'petwork') THEN
            CREATE SCHEMA petwork;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'petwork') THEN
            CREATE SCHEMA petwork;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE EXTENSION IF NOT EXISTS citext;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE TABLE petwork."Badges" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        "IconUrl" text NOT NULL,
        CONSTRAINT "PK_Badges" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE TABLE petwork."Diseases" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        "Description" text NOT NULL,
        "Symptoms" text,
        "Treatments" text,
        "Treatment" text,
        "Prevention" text,
        "PetType" text,
        "AnimalType" text,
        "FeaturedImage" text NOT NULL,
        "Category" text,
        "SeverityLevel" text,
        "ViewCount" integer NOT NULL DEFAULT 0,
        "PublishDate" timestamp without time zone NOT NULL DEFAULT TIMESTAMP '-infinity',
        CONSTRAINT "PK_Diseases" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE TABLE petwork."Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Username" citext NOT NULL,
        "Email" citext NOT NULL,
        "PasswordHash" text NOT NULL,
        "Bio" text,
        "ProfileImage" text NOT NULL,
        "RegistrationDate" timestamp without time zone NOT NULL,
        "ExperiencePoints" integer NOT NULL,
        "IsAdmin" boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE TABLE petwork."BadgeUser" (
        "BadgesId" integer NOT NULL,
        "UsersId" integer NOT NULL,
        CONSTRAINT "PK_BadgeUser" PRIMARY KEY ("BadgesId", "UsersId"),
        CONSTRAINT "FK_BadgeUser_Badges_BadgesId" FOREIGN KEY ("BadgesId") REFERENCES petwork."Badges" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_BadgeUser_Users_UsersId" FOREIGN KEY ("UsersId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE TABLE petwork."BlogPosts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(200) NOT NULL,
        "Content" text NOT NULL,
        "Category" text NOT NULL,
        "FeaturedImage" text NOT NULL,
        "ImageUrl" text NOT NULL,
        "PublishedDate" timestamp without time zone NOT NULL,
        "PublishDate" timestamp without time zone NOT NULL,
        "ViewCount" integer NOT NULL,
        "UserId" integer NOT NULL,
        CONSTRAINT "PK_BlogPosts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BlogPosts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE TABLE petwork."Guides" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(200) NOT NULL,
        "Description" text NOT NULL,
        "Content" text NOT NULL,
        "AnimalType" text,
        "Category" text,
        "Level" text,
        "ViewCount" integer NOT NULL,
        "PublishDate" timestamp without time zone NOT NULL,
        "UserId" integer NOT NULL,
        CONSTRAINT "PK_Guides" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Guides_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE TABLE petwork."Pets" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(50) NOT NULL,
        "Type" text NOT NULL,
        "PetType" text NOT NULL DEFAULT '',
        "Breed" text,
        "DateOfBirth" date,
        "Age" integer,
        "Gender" text,
        "ProfileImage" text NOT NULL,
        "Image" text,
        "Description" text,
        "UserId" integer NOT NULL,
        CONSTRAINT "PK_Pets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Pets_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE TABLE petwork."Questions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(200) NOT NULL,
        "Content" text NOT NULL,
        "Category" text,
        "Tags" text,
        "CreatedDate" timestamp without time zone NOT NULL,
        "ViewCount" integer NOT NULL,
        "UserId" integer NOT NULL,
        CONSTRAINT "PK_Questions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Questions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE TABLE petwork."Recipes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(200) NOT NULL,
        "Description" text NOT NULL DEFAULT '',
        "Ingredients" text NOT NULL,
        "Instructions" text NOT NULL,
        "Content" text NOT NULL,
        "PetType" text,
        "AnimalType" text,
        "DietType" text,
        "PreparationTime" integer NOT NULL DEFAULT 0,
        "FeaturedImage" text NOT NULL,
        "ImageUrl" text NOT NULL,
        "Difficulty" text NOT NULL,
        "PrepTime" text NOT NULL,
        "CreatedDate" timestamp without time zone NOT NULL,
        "PublishDate" timestamp without time zone NOT NULL,
        "ViewCount" integer NOT NULL,
        "UserId" integer NOT NULL,
        CONSTRAINT "PK_Recipes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Recipes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE TABLE petwork."Answers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Content" text NOT NULL,
        "CreatedDate" timestamp without time zone NOT NULL,
        "IsAccepted" boolean NOT NULL,
        "UpVotes" integer NOT NULL,
        "DownVotes" integer NOT NULL,
        "QuestionId" integer NOT NULL,
        "UserId" integer NOT NULL,
        CONSTRAINT "PK_Answers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Answers_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES petwork."Questions" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Answers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE INDEX "IX_Answers_QuestionId" ON petwork."Answers" ("QuestionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE INDEX "IX_Answers_UserId" ON petwork."Answers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE INDEX "IX_BadgeUser_UsersId" ON petwork."BadgeUser" ("UsersId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE INDEX "IX_BlogPosts_UserId" ON petwork."BlogPosts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE INDEX "IX_Guides_UserId" ON petwork."Guides" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE INDEX "IX_Pets_UserId" ON petwork."Pets" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE INDEX "IX_Questions_UserId" ON petwork."Questions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE INDEX "IX_Recipes_UserId" ON petwork."Recipes" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON petwork."Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    CREATE UNIQUE INDEX "IX_Users_Username" ON petwork."Users" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260904151614_InitialPostgreSql') THEN
    INSERT INTO petwork."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260904151614_InitialPostgreSql', '9.0.4');
    END IF;
END $EF$;
COMMIT;

