using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PetWork.Migrations.PostgreSql;

public partial class MobileAuthLifecycle : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // Convergent because an early production rollout created these tables before
        // this branch's migration id reached main.
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS petwork."MobileAuthSessions" (
                "Id" uuid NOT NULL,
                "UserId" integer NOT NULL,
                "RefreshTokenHash" character varying(64) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "LastUsedAt" timestamp with time zone,
                "AccessExpiresAt" timestamp with time zone,
                "RefreshExpiresAt" timestamp with time zone,
                "ExpiresAt" timestamp with time zone,
                "RevokedAt" timestamp with time zone,
                "ReplacedByTokenHash" character varying(64),
                CONSTRAINT "PK_MobileAuthSessions" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_MobileAuthSessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
            );

            ALTER TABLE petwork."MobileAuthSessions" ADD COLUMN IF NOT EXISTS "LastUsedAt" timestamp with time zone;
            ALTER TABLE petwork."MobileAuthSessions" ADD COLUMN IF NOT EXISTS "AccessExpiresAt" timestamp with time zone;
            ALTER TABLE petwork."MobileAuthSessions" ADD COLUMN IF NOT EXISTS "RefreshExpiresAt" timestamp with time zone;
            ALTER TABLE petwork."MobileAuthSessions" ADD COLUMN IF NOT EXISTS "ExpiresAt" timestamp with time zone;
            ALTER TABLE petwork."MobileAuthSessions" ADD COLUMN IF NOT EXISTS "ReplacedByTokenHash" character varying(64);
            UPDATE petwork."MobileAuthSessions"
               SET "LastUsedAt" = COALESCE("LastUsedAt", "CreatedAt"),
                   "RefreshExpiresAt" = COALESCE("RefreshExpiresAt", "ExpiresAt", "CreatedAt" + interval '1 day'),
                   "AccessExpiresAt" = COALESCE("AccessExpiresAt", LEAST(COALESCE("ExpiresAt", "CreatedAt" + interval '15 minutes'), "CreatedAt" + interval '15 minutes'));
            ALTER TABLE petwork."MobileAuthSessions" ALTER COLUMN "LastUsedAt" SET NOT NULL;
            ALTER TABLE petwork."MobileAuthSessions" ALTER COLUMN "AccessExpiresAt" SET NOT NULL;
            ALTER TABLE petwork."MobileAuthSessions" ALTER COLUMN "RefreshExpiresAt" SET NOT NULL;
            ALTER TABLE petwork."MobileAuthSessions" DROP COLUMN IF EXISTS "ExpiresAt";
            ALTER TABLE petwork."MobileAuthSessions" DROP COLUMN IF EXISTS "ReplacedByTokenHash";

            CREATE TABLE IF NOT EXISTS petwork."PasswordResetTokens" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "UserId" integer NOT NULL,
                "TokenHash" character varying(64) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "ExpiresAt" timestamp with time zone NOT NULL,
                "UsedAt" timestamp with time zone,
                CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_PasswordResetTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS "IX_MobileAuthSessions_RefreshTokenHash" ON petwork."MobileAuthSessions" ("RefreshTokenHash");
            CREATE INDEX IF NOT EXISTS "IX_MobileAuthSessions_UserId_RevokedAt_RefreshExpiresAt" ON petwork."MobileAuthSessions" ("UserId", "RevokedAt", "RefreshExpiresAt");
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_PasswordResetTokens_TokenHash" ON petwork."PasswordResetTokens" ("TokenHash");
            CREATE INDEX IF NOT EXISTS "IX_PasswordResetTokens_UserId_UsedAt_ExpiresAt" ON petwork."PasswordResetTokens" ("UserId", "UsedAt", "ExpiresAt");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "MobileAuthSessions", schema: "petwork");
        migrationBuilder.DropTable(name: "PasswordResetTokens", schema: "petwork");
    }
}
