START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE TABLE petwork."AdoptionListings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "PetName" character varying(50) NOT NULL,
        "Species" character varying(50) NOT NULL,
        "Breed" character varying(100),
        "AgeYears" integer,
        "Gender" character varying(20),
        "City" character varying(80) NOT NULL,
        "District" character varying(80),
        "HealthInfo" character varying(500) NOT NULL,
        "Story" character varying(2000) NOT NULL,
        "ImagePath" character varying(500) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_AdoptionListings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AdoptionListings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE TABLE petwork."ProductReviews" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Brand" character varying(100) NOT NULL,
        "ProductName" character varying(150) NOT NULL,
        "PetType" character varying(50) NOT NULL,
        "Experience" character varying(1500) NOT NULL,
        "TasteScore" integer NOT NULL,
        "IngredientScore" integer NOT NULL,
        "DigestionScore" integer NOT NULL,
        "ValueScore" integer NOT NULL,
        "ImagePath" character varying(500),
        "CreatedAt" timestamp without time zone NOT NULL,
        "IsDeleted" boolean NOT NULL,
        CONSTRAINT "PK_ProductReviews" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductReviews_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE TABLE petwork."AdoptionApplications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AdoptionListingId" integer NOT NULL,
        "UserId" integer NOT NULL,
        "Message" character varying(1000) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_AdoptionApplications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AdoptionApplications_AdoptionListings_AdoptionListingId" FOREIGN KEY ("AdoptionListingId") REFERENCES petwork."AdoptionListings" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AdoptionApplications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE TABLE petwork."AdoptionListingReports" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AdoptionListingId" integer NOT NULL,
        "UserId" integer NOT NULL,
        "Reason" character varying(500) NOT NULL,
        "IsResolved" boolean NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_AdoptionListingReports" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AdoptionListingReports_AdoptionListings_AdoptionListingId" FOREIGN KEY ("AdoptionListingId") REFERENCES petwork."AdoptionListings" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AdoptionListingReports_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE TABLE petwork."ProductReviewReports" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductReviewId" integer NOT NULL,
        "UserId" integer NOT NULL,
        "Reason" character varying(500) NOT NULL,
        "IsResolved" boolean NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_ProductReviewReports" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProductReviewReports_ProductReviews_ProductReviewId" FOREIGN KEY ("ProductReviewId") REFERENCES petwork."ProductReviews" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProductReviewReports_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE UNIQUE INDEX "IX_AdoptionApplications_AdoptionListingId_UserId" ON petwork."AdoptionApplications" ("AdoptionListingId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE INDEX "IX_AdoptionApplications_UserId" ON petwork."AdoptionApplications" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE UNIQUE INDEX "IX_AdoptionListingReports_AdoptionListingId_UserId" ON petwork."AdoptionListingReports" ("AdoptionListingId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE INDEX "IX_AdoptionListingReports_IsResolved_CreatedAt" ON petwork."AdoptionListingReports" ("IsResolved", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE INDEX "IX_AdoptionListingReports_UserId" ON petwork."AdoptionListingReports" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE INDEX "IX_AdoptionListings_City_CreatedAt" ON petwork."AdoptionListings" ("City", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE INDEX "IX_AdoptionListings_IsDeleted_Status_CreatedAt" ON petwork."AdoptionListings" ("IsDeleted", "Status", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE INDEX "IX_AdoptionListings_UserId" ON petwork."AdoptionListings" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE INDEX "IX_ProductReviewReports_IsResolved_CreatedAt" ON petwork."ProductReviewReports" ("IsResolved", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE UNIQUE INDEX "IX_ProductReviewReports_ProductReviewId_UserId" ON petwork."ProductReviewReports" ("ProductReviewId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE INDEX "IX_ProductReviewReports_UserId" ON petwork."ProductReviewReports" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE INDEX "IX_ProductReviews_IsDeleted_CreatedAt" ON petwork."ProductReviews" ("IsDeleted", "CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    CREATE INDEX "IX_ProductReviews_UserId" ON petwork."ProductReviews" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260909111021_AddAdoptionAndProductReviews') THEN
    INSERT INTO petwork."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260909111021_AddAdoptionAndProductReviews', '9.0.4');
    END IF;
END $EF$;
COMMIT;
