BEGIN;

CREATE TABLE IF NOT EXISTS petwork."MobileSupportReports" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "Category" character varying(40) NOT NULL,
    "Description" character varying(3000) NOT NULL,
    "ScreenshotPath" character varying(500),
    "TrackingNumber" character varying(24) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "FK_MobileSupportReports_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_MobileSupportReports_Status_CreatedAt"
    ON petwork."MobileSupportReports" ("Status", "CreatedAt");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_MobileSupportReports_TrackingNumber"
    ON petwork."MobileSupportReports" ("TrackingNumber");
CREATE INDEX IF NOT EXISTS "IX_MobileSupportReports_UserId"
    ON petwork."MobileSupportReports" ("UserId");

-- Kimlik doğrulama ve kullanıcı yetkilendirmesi ASP.NET API katmanında yapılır.
-- Doğrudan Supabase istemcisine açık politika bırakılmaz; yalnızca backend rolüne erişim verilir.
GRANT USAGE ON SCHEMA petwork TO petwork_app;
ALTER TABLE petwork."MobileSupportReports" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE petwork."MobileSupportReports" DISABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE petwork."MobileSupportReports" TO petwork_app;
GRANT USAGE, SELECT ON SEQUENCE petwork."MobileSupportReports_Id_seq" TO petwork_app;

-- Supabase tarafında RLS daha sonra yeniden etkinleştirilse bile yalnızca backend rolü
-- kayıtları yönetebilsin. petwork_app üyeliğiyle bağlanan pooler kullanıcıları da kapsanır.
DROP POLICY IF EXISTS "MobileSupportReports_backend" ON petwork."MobileSupportReports";
CREATE POLICY "MobileSupportReports_backend"
    ON petwork."MobileSupportReports"
    FOR ALL
    TO petwork_app
    USING (true)
    WITH CHECK (true);

INSERT INTO petwork."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260912135836_AddMobileSupportReportsPostgres', '9.0.4'
WHERE NOT EXISTS (
    SELECT 1 FROM petwork."__EFMigrationsHistory"
    WHERE "MigrationId" = '20260912135836_AddMobileSupportReportsPostgres'
);

COMMIT;
