BEGIN;

CREATE TABLE IF NOT EXISTS petwork."PatiMatchContactShares" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PetOneId" integer NOT NULL,
    "PetTwoId" integer NOT NULL,
    "SharedByUserId" integer NOT NULL,
    "Phone" character varying(30),
    "ContactEmail" character varying(254),
    "SharedAt" timestamp without time zone NOT NULL,
    "RevokedAt" timestamp without time zone,
    CONSTRAINT "FK_PatiMatchContactShares_Pets_PetOneId"
        FOREIGN KEY ("PetOneId") REFERENCES petwork."Pets" ("Id"),
    CONSTRAINT "FK_PatiMatchContactShares_Pets_PetTwoId"
        FOREIGN KEY ("PetTwoId") REFERENCES petwork."Pets" ("Id"),
    CONSTRAINT "FK_PatiMatchContactShares_Users_SharedByUserId"
        FOREIGN KEY ("SharedByUserId") REFERENCES petwork."Users" ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_PatiMatchContactShares_PetOneId_PetTwoId_SharedByUserId"
    ON petwork."PatiMatchContactShares" ("PetOneId", "PetTwoId", "SharedByUserId");
CREATE INDEX IF NOT EXISTS "IX_PatiMatchContactShares_PetTwoId"
    ON petwork."PatiMatchContactShares" ("PetTwoId");
CREATE INDEX IF NOT EXISTS "IX_PatiMatchContactShares_SharedByUserId"
    ON petwork."PatiMatchContactShares" ("SharedByUserId");

ALTER TABLE petwork."PatiMatchContactShares" DISABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE petwork."PatiMatchContactShares" TO petwork_app;
GRANT USAGE, SELECT ON SEQUENCE petwork."PatiMatchContactShares_Id_seq" TO petwork_app;

INSERT INTO petwork."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260912125411_AddPatiMatchContactSharesPostgres', '9.0.4'
WHERE NOT EXISTS (
    SELECT 1 FROM petwork."__EFMigrationsHistory"
    WHERE "MigrationId" = '20260912125411_AddPatiMatchContactSharesPostgres'
);

COMMIT;
