BEGIN;

CREATE TABLE IF NOT EXISTS petwork."MobileNotificationPreferences" (
    "UserId" integer PRIMARY KEY,
    "CommunityNotifications" boolean NOT NULL DEFAULT FALSE,
    "LostPetNotifications" boolean NOT NULL DEFAULT FALSE,
    "MatchNotifications" boolean NOT NULL DEFAULT FALSE,
    "UpdatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "FK_MobileNotificationPreferences_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS petwork."MobilePushTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "Token" character varying(300) NOT NULL,
    "Platform" character varying(20),
    "UpdatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "FK_MobilePushTokens_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_MobilePushTokens_Token"
    ON petwork."MobilePushTokens" ("Token");
CREATE INDEX IF NOT EXISTS "IX_MobilePushTokens_UserId"
    ON petwork."MobilePushTokens" ("UserId");

CREATE TABLE IF NOT EXISTS petwork."MobileMediaAssets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "StorageKey" character varying(500) NOT NULL,
    "ContentType" character varying(50) NOT NULL,
    "Data" bytea NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_MobileMediaAssets_StorageKey"
    ON petwork."MobileMediaAssets" ("StorageKey");

UPDATE petwork."AdoptionListings" AS listing
SET "Status" = 'adopted'
WHERE listing."Status" = 'active'
  AND EXISTS (
      SELECT 1 FROM petwork."AdoptionApplications" AS application
      WHERE application."AdoptionListingId" = listing."Id"
        AND application."Status" = 'accepted'
  );

INSERT INTO petwork."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT migration."MigrationId", migration."ProductVersion"
FROM (VALUES
    ('20260909191054_AddNotificationPreferencesAndPushTokens', '9.0.4'),
    ('20260909212928_StoreMobileMediaInDatabase', '9.0.4')
) AS migration("MigrationId", "ProductVersion")
WHERE NOT EXISTS (
    SELECT 1 FROM petwork."__EFMigrationsHistory" AS history
    WHERE history."MigrationId" = migration."MigrationId"
);

COMMIT;
