BEGIN;

CREATE TABLE IF NOT EXISTS petwork."MobileNotifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "Type" character varying(40) NOT NULL,
    "Title" character varying(120) NOT NULL,
    "Body" character varying(500) NOT NULL,
    "EntityType" character varying(40),
    "EntityId" integer,
    "IsRead" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "FK_MobileNotifications_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_MobileNotifications_UserId_IsRead_CreatedAt"
    ON petwork."MobileNotifications" ("UserId", "IsRead", "CreatedAt");

INSERT INTO petwork."MobileNotifications"
    ("UserId", "Type", "Title", "Body", "EntityType", "EntityId", "IsRead", "CreatedAt")
SELECT l."UserId", 'lost_sighting', l."PetName" || ' için yeni görülme bildirimi',
       s."LocationLabel" || ' konumunda yeni bir gözlem paylaşıldı.', 'lost_pet', l."Id", FALSE, s."CreatedAt"
FROM petwork."LostPetSightings" s
JOIN petwork."LostPetListings" l ON l."Id" = s."LostPetListingId"
WHERE NOT s."IsDeleted"
  AND NOT EXISTS (
      SELECT 1 FROM petwork."MobileNotifications" n
      WHERE n."UserId" = l."UserId" AND n."Type" = 'lost_sighting'
        AND n."EntityType" = 'lost_pet' AND n."EntityId" = l."Id" AND n."CreatedAt" = s."CreatedAt"
  );

INSERT INTO petwork."MobileNotifications"
    ("UserId", "Type", "Title", "Body", "EntityType", "EntityId", "IsRead", "CreatedAt")
SELECT l."UserId", 'adoption_application', l."PetName" || ' için yeni başvuru',
       '@' || u."Username" || ' sahiplendirme ilanına başvurdu.', 'adoption', l."Id", FALSE, a."CreatedAt"
FROM petwork."AdoptionApplications" a
JOIN petwork."AdoptionListings" l ON l."Id" = a."AdoptionListingId"
JOIN petwork."Users" u ON u."Id" = a."UserId"
WHERE NOT EXISTS (
    SELECT 1 FROM petwork."MobileNotifications" n
    WHERE n."UserId" = l."UserId" AND n."Type" = 'adoption_application'
      AND n."EntityType" = 'adoption' AND n."EntityId" = l."Id" AND n."CreatedAt" = a."CreatedAt"
);

INSERT INTO petwork."MobileNotifications"
    ("UserId", "Type", "Title", "Body", "EntityType", "EntityId", "IsRead", "CreatedAt")
SELECT a."UserId", 'adoption_status', l."PetName" || ' başvurun güncellendi',
       CASE WHEN a."Status" = 'accepted' THEN 'Sahiplendirme başvurun kabul edildi.' ELSE 'Sahiplendirme başvurun reddedildi.' END,
       'adoption', l."Id", FALSE, LOCALTIMESTAMP
FROM petwork."AdoptionApplications" a
JOIN petwork."AdoptionListings" l ON l."Id" = a."AdoptionListingId"
WHERE a."Status" IN ('accepted', 'rejected')
  AND NOT EXISTS (
      SELECT 1 FROM petwork."MobileNotifications" n
      WHERE n."UserId" = a."UserId" AND n."Type" = 'adoption_status'
        AND n."EntityType" = 'adoption' AND n."EntityId" = l."Id"
  );

INSERT INTO petwork."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260909151908_AddMobileNotifications', '9.0.4'
WHERE NOT EXISTS (
    SELECT 1 FROM petwork."__EFMigrationsHistory"
    WHERE "MigrationId" = '20260909151908_AddMobileNotifications'
);

COMMIT;
