BEGIN;

CREATE TABLE IF NOT EXISTS petwork."MobileNotificationPreferences" (
    "UserId" integer PRIMARY KEY,
    "CommunityNotifications" boolean NOT NULL DEFAULT FALSE,
    "LostPetNotifications" boolean NOT NULL DEFAULT FALSE,
    "MatchNotifications" boolean NOT NULL DEFAULT FALSE,
    "UpdatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "FK_MobileNotificationPreferences_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS petwork."MobilePushTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "Token" character varying(300) NOT NULL,
    "Platform" character varying(20),
    "UpdatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "FK_MobilePushTokens_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_MobilePushTokens_Token"
    ON petwork."MobilePushTokens" ("Token");
CREATE INDEX IF NOT EXISTS "IX_MobilePushTokens_UserId"
    ON petwork."MobilePushTokens" ("UserId");

UPDATE petwork."AdoptionListings" AS listing
SET "Status" = 'adopted'
WHERE listing."Status" = 'active'
  AND EXISTS (
      SELECT 1 FROM petwork."AdoptionApplications" AS application
      WHERE application."AdoptionListingId" = listing."Id"
        AND application."Status" = 'accepted'
  );

INSERT INTO petwork."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260909191054_AddNotificationPreferencesAndPushTokens', '9.0.4'
WHERE NOT EXISTS (
    SELECT 1 FROM petwork."__EFMigrationsHistory"
    WHERE "MigrationId" = '20260909191054_AddNotificationPreferencesAndPushTokens'
);

COMMIT;
