START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260908135338_AddSocialReactionsPostgres') THEN
    CREATE TABLE petwork."SocialCommentLikes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SocialCommentId" integer NOT NULL,
        "UserId" integer NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_SocialCommentLikes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SocialCommentLikes_SocialComments_SocialCommentId" FOREIGN KEY ("SocialCommentId") REFERENCES petwork."SocialComments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SocialCommentLikes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260908135338_AddSocialReactionsPostgres') THEN
    CREATE TABLE petwork."SocialPostLikes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SocialPostId" integer NOT NULL,
        "UserId" integer NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_SocialPostLikes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SocialPostLikes_SocialPosts_SocialPostId" FOREIGN KEY ("SocialPostId") REFERENCES petwork."SocialPosts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SocialPostLikes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260908135338_AddSocialReactionsPostgres') THEN
    CREATE TABLE petwork."SocialPostSaves" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SocialPostId" integer NOT NULL,
        "UserId" integer NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_SocialPostSaves" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SocialPostSaves_SocialPosts_SocialPostId" FOREIGN KEY ("SocialPostId") REFERENCES petwork."SocialPosts" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_SocialPostSaves_Users_UserId" FOREIGN KEY ("UserId") REFERENCES petwork."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260908135338_AddSocialReactionsPostgres') THEN
    CREATE UNIQUE INDEX "IX_SocialCommentLikes_SocialCommentId_UserId" ON petwork."SocialCommentLikes" ("SocialCommentId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260908135338_AddSocialReactionsPostgres') THEN
    CREATE INDEX "IX_SocialCommentLikes_UserId" ON petwork."SocialCommentLikes" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260908135338_AddSocialReactionsPostgres') THEN
    CREATE UNIQUE INDEX "IX_SocialPostLikes_SocialPostId_UserId" ON petwork."SocialPostLikes" ("SocialPostId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260908135338_AddSocialReactionsPostgres') THEN
    CREATE INDEX "IX_SocialPostLikes_UserId" ON petwork."SocialPostLikes" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260908135338_AddSocialReactionsPostgres') THEN
    CREATE UNIQUE INDEX "IX_SocialPostSaves_SocialPostId_UserId" ON petwork."SocialPostSaves" ("SocialPostId", "UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260908135338_AddSocialReactionsPostgres') THEN
    CREATE INDEX "IX_SocialPostSaves_UserId" ON petwork."SocialPostSaves" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260908135338_AddSocialReactionsPostgres') THEN
    INSERT INTO petwork."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260908135338_AddSocialReactionsPostgres', '9.0.4');
    END IF;
END $EF$;
COMMIT;
