START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260908142222_AddLostPetsMobile') THEN
    CREATE TABLE IF NOT EXISTS petwork."LostPetListings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "UserId" integer NOT NULL REFERENCES petwork."Users" ("Id") ON DELETE CASCADE,
        "Kind" character varying(10) NOT NULL,
        "PetName" character varying(50) NOT NULL,
        "Species" character varying(50) NOT NULL,
        "Breed" character varying(100),
        "DistinguishingFeatures" character varying(1000) NOT NULL,
        "EventAt" timestamp without time zone NOT NULL,
        "City" character varying(80) NOT NULL,
        "District" character varying(80) NOT NULL,
        "Neighborhood" character varying(120),
        "Latitude" double precision,
        "Longitude" double precision,
        "CollarOrMicrochip" character varying(500),
        "Notes" character varying(1500),
        "ImagePath" character varying(500) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "SourceName" character varying(100) NOT NULL,
        "SourceUrl" character varying(1000),
        "ExternalId" character varying(200),
        "CreatedAt" timestamp without time zone NOT NULL,
        "ExpiresAt" timestamp without time zone NOT NULL,
        "IsDeleted" boolean NOT NULL
    );

    CREATE TABLE IF NOT EXISTS petwork."LostPetSightings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "LostPetListingId" integer NOT NULL REFERENCES petwork."LostPetListings" ("Id") ON DELETE CASCADE,
        "UserId" integer NOT NULL REFERENCES petwork."Users" ("Id") ON DELETE RESTRICT,
        "LocationLabel" character varying(200) NOT NULL,
        "SeenAt" timestamp without time zone NOT NULL,
        "Note" character varying(1000),
        "Latitude" double precision,
        "Longitude" double precision,
        "CreatedAt" timestamp without time zone NOT NULL,
        "IsDeleted" boolean NOT NULL
    );

    CREATE INDEX IF NOT EXISTS "IX_LostPetListings_City_District_CreatedAt"
        ON petwork."LostPetListings" ("City", "District", "CreatedAt");
    CREATE INDEX IF NOT EXISTS "IX_LostPetListings_IsDeleted_Status_ExpiresAt"
        ON petwork."LostPetListings" ("IsDeleted", "Status", "ExpiresAt");
    CREATE INDEX IF NOT EXISTS "IX_LostPetListings_UserId"
        ON petwork."LostPetListings" ("UserId");
    CREATE INDEX IF NOT EXISTS "IX_LostPetSightings_LostPetListingId_IsDeleted_SeenAt"
        ON petwork."LostPetSightings" ("LostPetListingId", "IsDeleted", "SeenAt");
    CREATE INDEX IF NOT EXISTS "IX_LostPetSightings_UserId"
        ON petwork."LostPetSightings" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM petwork."__EFMigrationsHistory" WHERE "MigrationId" = '20260908142222_AddLostPetsMobile') THEN
    INSERT INTO petwork."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260908142222_AddLostPetsMobile', '9.0.4');
    END IF;
END $EF$;
COMMIT;
